### ISSUE TITLE
Desyncing in 5.7

### ISSUE THREAD

**Issue by ljcarlin** [FasterMelee/FasterMelee-installer#34] opened 2017-09-25 02:25 UTC
I installed 5.7 using the script and when I start a game with someone else I immediatly desync.
Clicking on the gecko codes tab there are no codes, which might be the cause of the problem.

**Comment by Ptomerty** [comment] 2017-09-25 02:27
Nothing major should have changed. Do the `Sys/` and `User/` folders exist?

**Comment by ljcarlin** [comment] 2017-09-25 02:31
Yeah they do.

Should I try copying files from an earlier fm version? (I don't know what is where)

**Comment by ljcarlin** [comment] 2017-09-25 02:36
I forgot to say I'm using the pal netplay build

**Comment by Ptomerty** [comment] 2017-09-25 03:02
Oops, didn't mean to close the issue. TBH I'm not sure if PAL is supported; I'll check with Truck and get back to you.

**Comment by Ptomerty** [comment] 2017-09-25 19:48
After asking, the problem is that config files don't exist for PAL/JPN versions yet, and this will be fixed in 5.8. As a workaround (note: not recommended), copy GALE01r2.ini to GALP01r2.ini. Official support will come soon, with cleaned up headers.

Closing issue.

**Closed as completed by Ptomerty** 2017-09-25 19:48 UTC
